Trimaker - speed profile
prusa3d/PrusaSlicer-settings pull request #203
Opened 2023-07-19 16:17 UTC by MatiGabaglio16

Update for the Trimaker vendor bundle. The new version includes a profile for high speed

2023-07-25 05:19 UTC, rtyr requested changes
Please fix the things mentioned in the review.

Summary:
- change the version to 1.0.1 in both files (semantic versioning)
- remove incorrect keys (machine limits and slowdown does not belong to print profile)

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +config_version = 1.1.0
Please change the version to 1.0.1.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +machine_max_acceleration_x = 1500
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +machine_max_acceleration_y = 1500
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +machine_max_acceleration_extruding = 1500
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +machine_max_jerk_x = 15
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +machine_max_jerk_y = 15
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/1.1.0.ini
> +slowdown_below_layer_time = 0
Please remove this incorrect key.

2023-07-25 05:19 UTC, rtyr commented on live/Trimaker/index.idx
> +1.1.0 Speed profile has been added
Please change the version to 1.0.1.

2023-07-25 13:04 UTC, rtyr commented
version number in index.idx have to be also changed, otherwise it should be ok to merge

2023-07-25 13:14 UTC, merged

2023-09-13 13:39 UTC, MatiGabaglio16 commented
Hello, why are this changes not visible in prusa slicer yet?

2023-09-13 17:40 UTC, rtyr commented
The update is available from the moment this was merged, so roughly 2 months. I can see it in the slicer.